version: '3.8'
services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    env_file:
      - .env
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  db_data: